import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

// Utility function to get public URL for product images
export const getProductImageUrl = (imagePath) => {
  if (!imagePath)
    return "https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-image_large.png?v=1530129081";

  // If it's already a full URL, return as is (but replace broken placeholders)
  if (imagePath.startsWith("http")) {
    // Replace broken via.placeholder.com URLs with working placeholder
    if (imagePath.includes("via.placeholder.com")) {
      return "https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-image_large.png?v=1530129081";
    }
    return imagePath;
  }

  // Otherwise, get the public URL from Supabase Storage
  const { data } = supabase.storage
    .from("product-images")
    .getPublicUrl(imagePath);

  return data.publicUrl;
};

// Utility function to upload an image to the bucket
export const uploadProductImage = async (file, fileName) => {
  const { data, error } = await supabase.storage
    .from("product-images")
    .upload(fileName, file);

  if (error) throw error;

  // Return the path for storing in the database
  return data.path;
};

// Delete one or more product image paths from the storage bucket.
// Accepts paths saved in DB (e.g. "products/123-file.png") or
// full public URLs previously generated by `getProductImageUrl`.
export const deleteProductImages = async (paths = []) => {
  if (!Array.isArray(paths) || paths.length === 0) return;

  // Normalize paths: if a full public URL is passed, try to extract the
  // storage object path used when uploading.
  const normalized = paths
    .map((p) => {
      if (!p) return null;
      if (p.startsWith("http")) {
        try {
          const marker = "/storage/v1/object/public/product-images/";
          const idx = p.indexOf(marker);
          if (idx !== -1) return p.slice(idx + marker.length);
        } catch (e) {
          return null;
        }
        return null;
      }
      return p;
    })
    .filter(Boolean);

  if (normalized.length === 0) return;

  const { data, error } = await supabase.storage
    .from("product-images")
    .remove(normalized);

  if (error) throw error;
  return data;
};

export default supabase;
